### ISSUE TITLE
Create conda env for Chapter 3 fails to build scikit-learn-0.24.2

### ISSUE THREAD

**Issue by kai-majerus** [PacktPublishing/Machine-Learning-Engineering-with-Python-Second-Edition#80]
Apple M1, Ventura 13.4.1

Running the given command `conda env create -f mlewp-chapter03.yml` gives the below error.

I tried changing setuptools version to 59.6.0 (<60) as suggested by the error, but I get the same outcome.

```
Pip subprocess error:
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


      Traceback (most recent call last):
        File "/Users/kaimajerus/miniforge3/envs/mlewp-chapter03/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/kaimajerus/miniforge3/envs/mlewp-chapter03/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/kaimajerus/miniforge3/envs/mlewp-chapter03/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/bm/q77j4spj5nsbdchm0916yf5r0000gn/T/pip-build-env-q4oecenc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/bm/q77j4spj5nsbdchm0916yf5r0000gn/T/pip-build-env-q4oecenc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/bm/q77j4spj5nsbdchm0916yf5r0000gn/T/pip-build-env-q4oecenc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 301, in <module>
        File "<string>", line 293, in setup_package
        File "/private/var/folders/bm/q77j4spj5nsbdchm0916yf5r0000gn/T/pip-build-env-q4oecenc/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/private/var/folders/bm/q77j4spj5nsbdchm0916yf5r0000gn/T/pip-build-env-q4oecenc/overlay/lib/python3.10/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/private/var/folders/bm/q77j4spj5nsbdchm0916yf5r0000gn/T/pip-build-env-q4oecenc/overlay/lib/python3.10/site-packages/numpy/distutils/mingw32ccompiler.py", line 27, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by AndyMc629** [comment]
Sorry about this, will take a look ASAP.

**Comment by AndyMc629** [comment]
Found a potentially related issue on my M2, auto-sklearn can't install properly as it expects a linux kernel. On my old macbook I think I was able to get away with forcing (somehow) and x86_64 install, won't work here. Will find a workaround and send up. In meantime, this minimal conda yaml will get the other examples working [) pyspark ones, working on that too).

`name: mlewp-chapter03-hotfix
channels:
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - alembic=1.14.1
  - annotated-types=0.7.0
  - async-timeout=5.0.1
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bcrypt=4.2.1
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cachetools=5.5.1
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - contourpy=1.3.1
  - cryptography=44.0.0
  - cycler=0.12.1
  - databricks-sdk=0.43.0
  - deprecated=1.2.18
  - docker-py=7.1.0
  - entrypoints=0.4
  - flask=3.1.0
  - fonttools=4.55.8
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - google-auth=2.38.0
  - graphene=3.4.3
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.1.1
  - gunicorn=23.0.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libparquet=18.1.0
  - libpng=1.6.46
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4-c=1.10.0
  - mako=1.3.9
  - markdown=3.6
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - mlflow=2.20.1
  - mlflow-skinny=2.20.1
  - mlflow-ui=2.20.1
  - multidict=6.1.0
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - opentelemetry-api=1.16.0
  - opentelemetry-sdk=1.16.0
  - opentelemetry-semantic-conventions=0.37b0
  - optuna=4.2.0
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.2
  - paramiko=3.5.1
  - pillow=11.1.0
  - pip=25.0
  - prometheus_client=0.21.1
  - prometheus_flask_exporter=0.23.1
  - propcache=0.2.1
  - protobuf=5.28.3
  - pthread-stubs=0.4
  - py4j=0.10.9.7
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pynacl=1.5.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - pyspark=3.5.4
  - python=3.10.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytz=2024.2
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - querystring_parser=1.2.4
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=75.8.0
  - six=1.17.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sqlalchemy=2.0.37
  - sqlparse=0.5.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - yarl=1.18.3
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/mlewp-chapter03-hotfix
`

**Comment by AndyMc629** [comment]
This branch is where i'm working on fix. 80-create-conda-env-for-chapter-3-fails-to-build-scikit-learn-0242

**Comment by AndyMc629** [comment]
Ok so now have updated the yml file to work for all ch3 examples except the autosklearn example (issues now with autosklearn and macos and windows) so I now have a docker based example there.
